const fs=require('fs'),path=require('path'),assert=require('assert');
const runtime=process.env.NR_PLAYWRIGHT||'C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright';
const {chromium}=require(runtime),base=process.env.NR_PORTAL_URL||'http://127.0.0.1:8874/';
const output=process.env.NR_TEST_OUTPUT||path.resolve(__dirname,'../data/mb-budget-sync/nr-test-output');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],failures=[],results=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)failures.push(r.status()+' '+r.url());});
 await page.goto(base+'?v=nr-py-test&tab=zonalfr');await page.waitForTimeout(900);
 const codes=await page.evaluate(()=>Object.keys(NR_ZONE_DATA.scopes)),tabs=['summary','liability','smhdetail','demandsmh','pumaster','monthwise','bpanalysis','budgetcontrol','excessshortfall','trend','aitrend','historycompare'];
 assert.equal(codes.length,23);
 for(const code of codes){
  await page.evaluate(code=>applyNRScope(code),code);
  const check=await page.evaluate(()=>({selected:NR_SELECTED_SCOPE.code,py:NR_SELECTED_PY_SCOPE.code,months:Object.keys(MONTH_PY.TOTAL).length,actual:BUDGET_PY.TOTAL.actuals_till,monthly:Object.values(MONTH_PY.TOTAL).reduce((s,n)=>s+n,0)}));assert.equal(check.selected,code);assert.equal(check.py,code);assert.equal(check.months,12);assert.equal(check.actual,check.monthly);
  for(const tab of tabs){await page.evaluate(tab=>{switchTab(tab);setReportViewMode('classic');},tab);await page.waitForTimeout(20);const table=page.locator('#tab-'+tab+' .nr-py-table');assert.equal(await table.count(),1,code+':'+tab);if(!await table.isVisible()){console.log(await page.evaluate(()=>({body:document.body.className,active:[...document.querySelectorAll('.tab-content.active')].map(e=>e.id),hidden:[...document.querySelectorAll('#tab-liability .nr-py-panel,#tab-liability')].map(e=>({id:e.id,hidden:e.hidden,style:e.style.cssText,display:getComputedStyle(e).display}))})));await page.screenshot({path:path.join(output,'failed.png')});}assert(await table.isVisible(),code+':'+tab);const capture=await page.evaluate(tab=>DisplayExport.capture(tab,{tableOnly:true}),tab);assert(capture.tables.some(t=>t.title==='Previous-year same-period comparison'),code+':'+tab);results.push({scope:code,tab,rows:await table.locator('tbody tr').count()});}
  console.log('PASS scope',code,tabs.length,'financial views');
 }
 await page.evaluate(()=>{applyNRScope('03');switchTab('zonalfr');selectFRPage('review');});
 const views=await page.locator('#frReviewView option').evaluateAll(o=>o.map(x=>x.value));
 for(const view of views){await page.selectOption('#frReviewView',view);if(view==='coverage')assert(!await page.locator('#tab-zonalfr .nr-py-panel').isVisible());else assert(await page.locator('#tab-zonalfr .nr-py-panel').isVisible());}
 await page.click('[data-fr-page=monitor]');for(const type of ['pu','dept','demand','month']){await page.selectOption('#frMonitoringType',type);await page.selectOption('#frCompareGroup','zone');assert(await page.locator('#tab-zonalfr .nr-py-table').isVisible());}
 await page.click('[data-fr-page=insight]');assert.equal(await page.inputValue('#frAIGroup'),'zone');assert.equal(await page.inputValue('#frInsightType'),'alert');for(const type of ['pu','dept','demand','month','all']){await page.selectOption('#frAIDimension',type);await page.selectOption('#frInsightType','all');assert(await page.locator('#tab-zonalfr .nr-py-table').isVisible());}
 await page.selectOption('#frAIDimension','pu');await page.selectOption('#frAIGroup','zoneSelected');await page.locator('#frAIAUsTicks summary').click();await page.locator('#frAIAUsTicks input[value="0307"]').check();await page.locator('#frAIHeadsTicks summary').click();await page.locator('#frAIHeadsTicks input[value="pu:10"]').check();await page.locator('#frAIHeadsTicks summary').click();assert.equal(await page.locator('#tab-zonalfr .nr-py-table tbody tr').count(),2);
 const checks=await page.evaluate(()=>{const p=NR_YEAR_COMPARE.compare('03','scope',NR_FR_REVIEW.period,true)[0],cy=NR_ZONE_DATA.scopes['03'].demand.rows.filter(r=>r.smh!=='10N'),py=NR_ZONE_PY_DATA.scopes['03'].demand.rows.filter(r=>r.smh!=='10N');return {p,cy:cy.reduce((s,r)=>s+NR_FR_REVIEW.actual(r.months),0),py:py.reduce((s,r)=>s+NR_FR_REVIEW.actual(r.months),0),partial:NR_YEAR_COMPARE.compare('0325','dept',NR_FR_REVIEW.period,true).every(r=>r.pyBudget==null)};});assert.equal(checks.p.cyActual,checks.cy);assert.equal(checks.p.pyActual,checks.py);assert(checks.partial);
 await page.screenshot({path:path.join(output,'nr-previous-year-insights.png')});
 await page.evaluate(()=>{getSelection().removeAllRanges();switchTab('trend');});await page.waitForTimeout(300);for(const style of ['bar','line','heat']){await page.selectOption('#nrGraphStyle',style);await page.waitForTimeout(80);}assert((await page.locator('#trendKPIStrip').innerText()).includes('same completed months'));
 await page.setViewportSize({width:390,height:900});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.setViewportSize({width:1440,height:1000});
 await page.evaluate(()=>{window.confirmProtectedExport=()=>true;});const downloads=[];page.on('download',d=>downloads.push(d));
 for(const tab of ['liability','smhdetail','demandsmh','monthwise','trend','zonalfr']){await page.evaluate(tab=>switchTab(tab),tab);for(const format of ['Excel','PDF','PPT']){const downloadPromise=page.waitForEvent('download',{timeout:30000});await page.evaluate(async ({format,tab})=>await DisplayExport.run(format,tab,{tableOnly:true}),{format,tab});const d=await downloadPromise;const ext={Excel:'xlsx',PDF:'pdf',PPT:'pptx'}[format];await d.saveAs(path.join(output,tab+'.'+ext));assert(d.suggestedFilename().endsWith('.'+ext));}}
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(failures.length,0,failures.join('\n'));
 const report={ok:true,generatedAt:new Date().toISOString(),scopes:codes.length,scopeViewChecks:results.length,frViews:views.length,exports:downloads.length,checks,errors,failures,results};fs.writeFileSync(path.join(output,'nr-portal-test.json'),JSON.stringify(report,null,2));console.log('PASS',report.scopeViewChecks,'scope/view checks;',views.length,'FR views;',downloads.length,'real exports; no browser errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
